### PR TITLE
Mark resnet acctests broken

### PR DESCRIPTION
**Pull request by ToucheSir**
These failing CI makes it harder to spot other failures, especially in downstream CI. Just a band-aid fix until we can get new weights generated.

### CODE REVIEW

**Comment by ToucheSir** [comment]
Ok, I think the last of the failures has been patched over and this is good to go. Do we want a separate issue to track regenerating weights for ResNet, WideResNet and ResNeXt?

**Comment by darsnack** [comment]
Line 128 of the `convents.jl` tests has `depth` as defined. Can you delete that variable?

**Comment by ToucheSir** [comment]
Also changed 139 since it looked similar, is that what you meant?

**Comment by ToucheSir** [comment]
Looks like that did the trick

**Review by darsnack — APPROVED** [review]

**Pull request merged**
