### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by cyborg1995**
Update instructions to download ImageNet dataset

### CODE REVIEW

**Review by lyndond — APPROVED** [review]
Looks fine to me and links work.

**Comment by DhairyaLGandhi** [comment]
Thanks, this looks fine, pity about the dataset. Can we retain the bit about placing the folder in the correct directory to be picked up?

**Comment by cyborg1995** [comment]
@DhairyaLGandhi sure.
Done!

**Review by DhairyaLGandhi — APPROVED** [review]

**Comment by DhairyaLGandhi** [comment]
Thanks!

**Pull request merged**
