### PR TITLE
use julia-actions/cache in CI

### PR DESCRIPTION
**Pull request by IanButterworth**
Just a fly-by suggestion while creating #259 

julia-actions/cache is now more powerful and stores precompile caches

### PR Checklist

- [ ] Tests are added
- [ ] Documentation, if applicable

### CODE REVIEW

**Review by ToucheSir — APPROVED** [review]
Nice to see it working now. How might we observe the performance improvements from caching? Also, is there an equivalent for Buildkite (to help solve our current timeout issues)?

**Comment by IanButterworth** [comment]
If you can, I recommend moving to the standard `julia-actions/julia-runtest` because it sets up coverage in a faster way and does parallel precompilation. The current setup here is hitting old serial precompilation (which is silently happening at the start of the test run)

**Comment by IanButterworth** [comment]
Multiplexing test groups via an env var that's handled in `runtests.jl` should be doable?

**Comment by ToucheSir** [comment]
Another problem: 
image
Trying to normalize these suite names would be more yaml-foo than I want to deal with right now (because we still need them for ReTest to work properly). Is there no way to make have the cache action work with them, given that they are still valid paths on *nix systems?

**Comment by IanButterworth** [comment]
That should be fixed upstream in the cache action

**Pull request merged**
