### PR TITLE
Fix the APIs of the new Model

### LINKED ISSUE #7: Part of the models cannot be accessed
In the following models, we cannot extract a part of the model hence usage as feature extractor is not currently possible

- [x] Google Net
- [x] ResNet
- [x] Densenet

This would essentially be refactoring the code into something similar to that in `model-zoo`. 

**This issue is just to track the progess**

### PR DESCRIPTION
**Pull request by avik-pal**
Fixes #7

### CODE REVIEW

**Comment by avik-pal** [comment]
@MikeInnes can you review this. I shall add the `densenet` model once I have the model-zoo equivalent of that ready

**Comment by avik-pal** [comment]
Commenting out the googlenet tests as Travis is unable to download `googlenet.bson`

**Comment by avik-pal** [comment]
The tests fail due to weights download failure

**Comment by MikeInnes** [comment]
I'm currently getting this error:

```julia
julia> Pkg.test("Metalhead")
INFO: Testing Metalhead
ERROR: LoadError: MethodError: no method matching Flux.Conv(::NNlib.#relu, ::Array{Float32,4}, ::Array{Float32,1}, ::Tuple{Int64,Int64}, ::Tuple{Int64,Int64}, ::Int64)
```

**Comment by avik-pal** [comment]
Yes I opened the issue regarding this here FluxML/Flux.jl#300

**Comment by avik-pal** [comment]
Atleast the current tests fails should go away with Flux `master`

**Comment by MikeInnes** [comment]
Thanks @avik-pal!

**Pull request merged**
