### PR TITLE
Added UNet architecture (inital commit)

### PR DESCRIPTION
**Pull request by ceferisbarov**
I added the model as-is and updated dependencies and utils. I created a new branch in my fork, but I cannot request to create a new branch in FluxML/Metalhead.jl.

[This](https://github.com/DhairyaLGandhi/UNet.jl) is the original model. I intend to add tests and integrate the model into Metalhead as much as possible.

### CODE REVIEW

**Comment by lorenzoh** [comment]
Agreed, FastAI.jl implementation also works with any backbone architecture by dynamically checking output sizes of each downscaling layer and adding the correct number of upsampling layers with skip connections. Also allows to drop some upscaling layers to get a lower-resolution output. This comes at the cost of not being 100% faithful to the UNet paper; instead it copies the approach from Python's fastai.

**Comment by ceferisbarov** [comment]
Thanks for the feedback. I can try and create a new PR. Any comments on this PR that would be relevant to other models, too?

**Comment by darsnack** [comment]
The overall approach in this PR is good. My only comment would have been to use `SkipConnection`s or `Parallel`, but if you follow FastAI.jl's design, then you should get that. In general, we try not to introduce a new type and `@functor` it unless it makes sense to do so.

**Comment by ceferisbarov** [comment]
I have decided to close this and open a new issue. Otherwise, it will get confusing.

**Pull request closed without merging**
