### PR TITLE
Release fixes

### PR DESCRIPTION
**Pull request by darsnack**
Some last minute fixes before releasing:
- Adaptive pooling layers are moved to classifier section instead of backbone
- Disabled the pre-trained models since we determined that the old weights are not producing accurate results; I don't think we should ship broken models
- Fix CI badge

### CODE REVIEW

**Comment by darsnack** [comment]
@lorenzoh will removing the pre-trained models cause issues for FastAI.jl? They shouldn't have been producing accurate results if you were using them.

**Comment by darsnack** [comment]
Training even the subset of models that we had before would take some time. Would you prefer to ship with the same pre-trained models but potentially inaccurate behavior?

**Comment by DhairyaLGandhi** [comment]
Yeah, I noticed the models behavior, agree we shouldn't be shipping them yet. I have some hardware that I'm waiting on that's earmarked for exactly this.

there's also a few other things, such as dropping the type params on the large models to avoid over specialisation, and a uniform API to separate access the backbone and relax the requirement to give the sizes of the inputs to create the models

**Comment by DhairyaLGandhi** [comment]
> Something like backbone(model) and classifier(model) okay?

Ideally the models would be the backbone themselves and classifiers can be added on top. That way our API surface is also low.

**Comment by darsnack** [comment]
But a ResNet50 specifies both a backbone and a classifier. If I write `model = ResNet50()` in my code and I get a model that doesn't include the classifier that is confusing. For research cases where reproducibility matters, it's important for us to return the exact model with easy ways to customize.

**Pull request merged**
