### PR TITLE
Release 0.7 (round 2)

### PR DESCRIPTION
**Pull request by darsnack**
I rebased #140 on #132 by accident, so #132 is already merged. No problem, it was ready. But this PR is to try and fix some of the memory pressure issues in the tests. Also an opportunity to suggest changes that should have been in #132.

### CODE REVIEW

**Comment by theabhirath** [comment]
Docs CI still seems to be erroring out for some reason 😬 Also, [this error](https://github.com/FluxML/Metalhead.jl/runs/5819603257?check_suite_focus=true#step:6:200) in the CI is one I've encountered occasionally locally as well (particularly when I update Flux and load it for the first time post precompilation). Not sure what the underlying package is, though.

**Comment by ToucheSir** [comment]
Unsure if the warnings have anything to do with the fatal error, but the first is https://github.com/JuliaMath/BFloat16s.jl/pull/37. The second I haven't seen before.

**Comment by theabhirath** [comment]
The second as in the `rpad` one? That's just because Flux 0.12.9 doesn't have MLUtils yet, so the `rpad` definition from Flux and the one from MLUtils (because Metalhead has MLUtils as a dep) are conflicting - should be solved when Flux 0.13 lands

**Comment by darsnack** [comment]
The CI failure might be completely unrelated and due to Publish.jl.

**Comment by darsnack** [comment]
Okay I think the release looks ready. @ToucheSir anything else? @theabhirath I replaced uses of `Diagonal` with the new and improved `Scale`. Are there any replacements possible with Flux 0.13 that I missed?

**Comment by ToucheSir** [comment]
Nope, I think this is good to go.

**Comment by theabhirath** [comment]
Seems perfect!

**Pull request merged**
